/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mutter_uninstallmonitor_MainApp */

#ifndef _Included_com_mutter_uninstallmonitor_MainApp
#define _Included_com_mutter_uninstallmonitor_MainApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mutter_uninstallmonitor_MainApp
 * Method:    forkUninstallMonitorProcess
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mutter_uninstallmonitor_MainApp_forkUninstallMonitorProcess
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
